MODEL:
  META_ARCHITECTURE: "TorchvisionClassifier"
  TVCLASSIFIER:
    NUM_CLASSES: 1000
    FLAVOR: "resnet50"
    PRETRAINED: True
  PIXEL_MEAN: (0.485, 0.456, 0.406)
  PIXEL_STD: (0.229, 0.224, 0.225)
DATASETS:
  TRAIN: ("imagenet",)
VERSION: 2